OnlineHelp/Areas/RepairTeam/Controllers/LoginRepairTeamController.cs
using Model.Dao;
using OnlineHelp.Areas.AdminManager.Models;
using OnlineHelp.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineHelp.Areas.RepairTeam.Controllers
{
    public class LoginRepairTeamController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var dao = new EmployeeDao();
                var result = dao.Login(model.UserName, Encryptor.MD5Hash(model.Password));
                if (result == 1)
                {
                    var user = dao.GetById(model.UserName);
                    var employeeSession = new EmployeeLogin();
                    employeeSession.UserName = user.UserName;
                    employeeSession.EmployeeID = user.ID;
                    employeeSession.Avatar = user.Avartar;
                    employeeSession.Name = user.Name;
                    employeeSession.Type = user.Type;
                    Session.Add(CommonConstants.EMPLOYEE_SESSION, employeeSession);
                    return RedirectToAction("Index", "HomeRepairTeam");
                }
                else if (result == 0)
                {
                    ModelState.AddModelError("", "Tài khoản không tồn tại.");
                }
                else if (result == -1)
                {
                    ModelState.AddModelError("", "Tài khoản đang bị khóa.");
                }
                else if (result == -2)
                {
                    ModelState.AddModelError("", "Mật khẩu không đúng.");
                }
                else
                {
                    ModelState.AddModelError("", "Đăng nhập không đúng.");
                }
            }
            return View("Index");
        }
    }
}

OnlineHelp/Areas/RepairTeam/Views/LoginRepairTeam/Index.cshtml
@model OnlineHelp.Areas.RepairTeam.Models.LoginRepairTeamModel
<!DOCTYPE HTML>
<html>
<head>
    <title>Pooled Admin Panel Category Flat Bootstrap Responsive Web Template | Sign In :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Pooled Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Bootstrap Core CSS -->
    <link href="/Assets/Admin/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
    <!-- Custom CSS -->
    <link href="/Assets/Admin/css/style.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="/Assets/Admin/css/morris.css" type="text/css" />
    <!-- Graph CSS -->
    <link href="/Assets/Admin/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="/Assets/Admin/css/jquery-ui.css">
    <!-- jQuery -->
    <script src="/Assets/Admin/js/jquery-2.1.4.min.js"></script>
    <!-- //jQuery -->
    <link href='/Assets/Admin/fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css' />
    <link href='/Assets/Admin/fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- lined-icons -->
    <link rel="stylesheet" href="/Assets/Admin/css/icon-font.min.css" type='text/css' />
    <!-- //lined-icons -->
</head>
<body>
    <div class="main-wthree">
        <div class="container">
            <div class="sin-w3-agile">
                <h2>Please log in</h2>
                @using (Html.BeginForm("Login", "LoginRepairTeam", FormMethod.Post))
                {
                    @Html.ValidationSummary(false, "", new { @class = "text-danger" });
                    <div class="username">
                        <span class="username">Username:</span>
                        @Html.TextBoxFor(model => model.UserName, new { @class = "name" })
                        <div class="clearfix"></div>
                    </div>
                    <div class="password-agileits">
                        <span class="username">Password:</span>
                        @Html.PasswordFor(model => model.Password, new { @class = "password" })
                        <div class="clearfix"></div>
                    </div>
                    <div class="login-w3">
                        <input type="submit" class="login" value="Login">
                    </div>
                    <div class="clearfix"></div>
                }
            </div>
        </div>
    </div>
</body>
</html>