OnlineHelp/Models/FeedBackViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineHelp.Models
{
    public class FeedBackViewModel
    {
        public string Name { get; set; }

        public string Email { get; set; }

        public int Phone { get; set; }

        public string Description { get; set; }

        public DateTime CreatedAt { get; set; }

        public int UserId { get; set; }
    }
}

OnlineHelp/Areas/AdminManager/Controllers/FeedBackController.cs
using Model.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineHelp.Areas.AdminManager.Controllers
{
    public class FeedBackController : BaseController
    {
        // GET: AdminManager/FeedBack
        public ActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            var dao = new FeedBackDao();
            var model = dao.ListAllPaging(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            
            return View(model);
        }

        [HttpPost]
        public JsonResult ChangeStatus(int id)
        {
            var result = new FeedBackDao().ChangeStatus(id);
            return Json(new
            {
                status = result
            });
        }
    }
}

OnlineHelp/Areas/AdminManager/Views/FeedBack/Index.cshtml
@model PagedList.IPagedList<Model.EF.FeedBack>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/AdminManager/Views/Shared/LayoutAdmin.cshtml";
}
@section jsFooter{
    <script src="~/Assets/Admin/js/controller/feedbackController.js"></script>
}
@using (Html.BeginForm("Index", "FeedBack", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-7">
            <h2>Feedback list</h2>
        </div>
        <div style="margin-top:20px" class="col-md-5">
            <div class="col-md-8">
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" value="@ViewBag.searchString" type="text" placeholder="Search" name="searchString">
                </form>
            </div>
            <div class="col-md-4">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
            </div>
        </div>
    </div>
}
<div class="w3l-table-info">
    <table id="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Description</th>
                <th>Phone</th>
                <th>Status</th>
                <th>Manipulation</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="row_@item.Id">
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Email</td>
                    <td>@item.Description</td>
                    <td>@item.Phone</td>
                    <td>
                        @if (item.Status == 0)
                        {
                            <a style="background-color: red; border-radius: 4px; padding: 4px; width: 70px;text-align:center;text-decoration:none;color:white;" class="btn-active " data-id="@item.Id" href="#">Lock</a>
                        }
                        else if (item.Status == 1)
                        {
                            <a style="background-color: green; border-radius: 4px; padding: 4px; width: 70px;text-align:center;text-decoration:none;color:white;" class="btn-active" data-id="@item.Id" href="#">Open</a>
                        }
                    </td>
                    <td>
                        <a href="#" class="deleteDes" data-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
</div>
<script>
    $('#table').basictable();
</script>

