OnlineHelp/Areas/RepairTeam/Controllers/RequestRepairTeamController.cs
using Common;
using Model.Dao;
using Model.EF;
using OnlineHelp.Common;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineHelp.Areas.RepairTeam.Controllers
{
    public class RequestRepairTeamController : BaseRepairTeamController
    {
        OnlineHelpDbContext db = new OnlineHelpDbContext();
        // GET: RepairTeam/RequestRepairTeam
        public ActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            var dao = new RequestRepairTeamDao();
            var typeEmloyee = (EmployeeLogin)Session[CommonConstants.EMPLOYEE_SESSION];
            var model = dao.ListAllPaging(searchString, page, pageSize, typeEmloyee.Type);
            ViewBag.SearchString = searchString;
            ViewBag.ListFacility = dao.ListFacility();
            ViewBag.ListGeneral = dao.ListGeneral();
            ViewBag.ListRoom = dao.ListRoom();
            return View(model);
        }

        [HttpPost]
        public JsonResult ChangeStatus(int id)
        {
            var result = new RequestDao().ChangeStatus(id);
            var request = db.Requests.Find(id);
            if (request.Status == 2)
            {
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Assets/Client/template/finishrequest.html"));

                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                new MailHelper().SendMail(request.Email, "Yêu cầu gửi từ OnlineHelp", content);
                new MailHelper().SendMail(toEmail, "Yêu cầu gửi từ OnlineHelp", content);

                return Json(new
                {
                    status = 2
                });
            }
            else if(request.Status == 1)
            {
                return Json(new
                {
                    status = 1
                });
            }
            else
            {
                return Json(new
                {
                    status = 0
                });
            }
        }

        
    }
}

OnlineHelp/Areas/RepairTeam/Views/RequestRepairTeam/Index.cshtml
@model PagedList.IPagedList<Model.EF.Request>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/RepairTeam/Views/Shared/_LayoutRepairTeam.cshtml";
}

@section jsFooter{
    <script src="~/Assets/Admin/js/controller/requestRepairTeamController.js"></script>
}
@using (Html.BeginForm("Index", "RequestRepairTeam", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-7">
            <h2>List Request</h2>
        </div>
        <div style="margin-top:20px" class="col-md-5">
            <div class="col-md-8">
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" value="@ViewBag.searchString" type="text" placeholder="Search" name="searchString">
                </form>
            </div>
            <div class="col-md-4">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
            </div>
        </div>
    </div>
}
<div class="w3l-table-info">
    <table id="table">
        <thead>
            <tr>
                <th>RequestID</th>
                <th>Requestor</th>
                <th>Facility</th>
                <th>Room</th>
                <th>Description</th>
                <th>Status</th>
                <th>Level</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr id="row_@item.RequestID">
                <td>@item.RequestID</td>
                <td>@item.Requestor</td>
                <td>
                    @foreach (var general in ViewBag.ListGeneral)
                    {
                        if (general.Id == item.GeneralID)
                        {
                            foreach (var facility in ViewBag.ListFacility)
                            {
                                if (facility.Id == general.FacilityId)
                                {
                                    @facility.Name;
                                    break;
                                }
                            }
                            break;
                        }
                    }
                </td>
                <td>
                    @foreach (var general in ViewBag.ListGeneral)
                    {
                        if (general.Id == item.GeneralID)
                        {
                            foreach (var room in ViewBag.ListRoom)
                            {
                                if (room.Id == general.RoomId)
                                {
                                    @room.Name;
                                    break;
                                }
                            }
                            break;
                        }
                    }
                </td>

                <td>@item.Description</td>
                <td>

                    @if (item.Status == 0)
                    {
                    <a style="background-color: #867979; border-radius: 4px; padding: 4px; width: 70px;text-align:center;text-decoration:none;color:white;" class="btn-active " data-id="@item.RequestID" href="#">Undefined</a>
                    }
                    else if (item.Status == 1)
                    {
                    <a style="background-color: red; border-radius: 4px; padding: 4px; width: 70px;text-align:center;text-decoration:none;color:white;" class="btn-active" data-id="@item.RequestID" href="#">Fixing</a>
                    }
                    else
                    {
                        <a style="background-color: green; border-radius: 4px; padding: 4px; width: 70px;text-align:center;text-decoration:none;color:white;" class="btn-active" data-id="@item.RequestID" href="#">Finish</a>
                    }

                </td>
                <td>
                    @if (item.Level == 0)
                    {
                        <a style="background-color:#FFC300; border-radius: 4px; padding: 4px; width: 70px;text-align:center;text-decoration:none;color:white;" data-id="@item.RequestID" href="#">Fix Now</a>
                    }
                    else if (item.Level == 1)
                    {
                        <a style="background-color: red; border-radius: 4px; padding: 4px; width: 70px;text-align:center;text-decoration:none;color:white;" data-id="@item.RequestID" href="#">Serious</a>
                    }
                    else if (item.Level == 2)
                    {
                        <a style="background-color: #867979; border-radius: 4px; padding: 4px; width: 70px;text-align:center;text-decoration:none;color:white;" data-id="@item.RequestID" href="#">Edit later</a>
                    }
                </td>
            </tr>
            }
        </tbody>
    </table>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
</div>
<script>
    $('#table').basictable();
</script>
